# Generated by Django 4.1 on 2024-08-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.IntegerField(unique=True)),
                ('probability', models.FloatField()),
                ('fun_fact', models.CharField(max_length=255)),
            ],
        ),
    ]
